apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "infra-otel-collector.fullname" . }}-config
  labels:
    {{- include "infra-otel-collector.labels" . | nindent 4 }}
data:
  otel-collector.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

      hostmetrics:
        collection_interval: 60s
        root_path: /hostfs
        scrapers:
          cpu:
            metrics:
              system.cpu.utilization:
                enabled: true
          memory:
            metrics:
              system.memory.utilization:
                enabled: true
          disk: {}
          filesystem:
            metrics:
              system.filesystem.utilization:
                enabled: true
          network: {}
          load: {}
          processes: {}

      kubeletstats:
        collection_interval: 60s
        auth_type: serviceAccount
        endpoint: "https://${env:K8S_NODE_IP}:10250"
        insecure_skip_verify: true
        metric_groups:
          - node
          - pod
          - container

      k8s_cluster:
        collection_interval: 60s
        auth_type: serviceAccount

      prometheus:
        config:
          scrape_configs:
            - job_name: otel-collector-self
              scrape_interval: 60s
              static_configs:
                - targets: ["localhost:8888"]

    processors:
      resource:
        attributes:
          - key: deployment.environment
            value: ${env:NODE_ENV}
            action: upsert
          - key: k8s.node.name
            from_attribute: k8s.node.name
            action: insert

      k8sattributes:
        auth_type: serviceAccount
        passthrough: false
        extract:
          metadata:
            - k8s.pod.name
            - k8s.pod.uid
            - k8s.deployment.name
            - k8s.namespace.name
            - k8s.node.name

      batch:
        timeout: 10s
        send_batch_size: 1024

      memory_limiter:
        check_interval: 5s
        limit_mib: 256
        spike_limit_mib: 64

    exporters:
      otlp/signoz:
        endpoint: ${env:OTLP_ENDPOINT}
        tls:
          insecure: false
        headers:
          signoz-access-token: ${env:OTEL_EXPORTER_OTLP_HEADERS}

      logging:
        verbosity: basic

    extensions:
      health_check:
        endpoint: 0.0.0.0:13133

    service:
      extensions: [health_check]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [otlp/signoz]

        metrics:
          receivers: [otlp, hostmetrics, kubeletstats, k8s_cluster, prometheus]
          processors: [memory_limiter, resource, k8sattributes, batch]
          exporters: [otlp/signoz]

        logs:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [otlp/signoz]
