name: Build and Deploy HOMOL

on:
  push:
    branches:
      - staging
  workflow_dispatch:
    inputs:
      uninstall:
        description: "Uninstall Helm release"
        required: false
        default: false
        type: boolean

env:
  NAMESPACE: monitoring
  APPNAME: infra-otel-collector
  K8S_CLUSTER: rancher-homol

jobs:
  deploy:
    uses: we-qi/sre-devops-github-workflow/.github/workflows/generic-build-scan-deploy.yml@main
    with:
      environment_name: homol
      runner_name: docker-runner-weqi
      kube_context: rancher-homol
      namespace: monitoring
      app_name: infra-otel-collector
      chart_path: ./helm
      values_file: ./helm/values-homol.yaml
      dockerfile_path: docker/Dockerfile
      proxy_configmap_name: proxy-homol
      uninstall: ${{ github.event_name == 'workflow_dispatch' && inputs.uninstall || false }}
    secrets: inherit
